name: Building Image

on:
  push:
    tags:
      - v*

env:
  ALIYUN_IMAGE_TOKEN: ${{ secrets.ALIYUN_IMAGE_ACCESSTOKEN }}

jobs:
  build:
    name: Building Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build the docker image
        run: |
          docker build -t app .
      - name: Tag the image
        run: |
          docker tag app registry.cn-shenzhen.aliyuncs.com/yansongda-app/miniprogram-api:$GITHUB_REF_NAME
      - name: Push the image to aliyun registry
        run: |
          echo $ALIYUN_IMAGE_TOKEN | docker login --username=me@yansongda.cn registry.cn-shenzhen.aliyuncs.com --password-stdin
          docker push registry.cn-shenzhen.aliyuncs.com/yansongda-app/miniprogram-api:$GITHUB_REF_NAME
          docker logout
